// ============================================================
// OpenClaw Installation Logic
// ============================================================

use std::process::Command;
use std::path::PathBuf;
use crate::node;

/// Install OpenClaw via npm
pub fn install_openclaw() -> Result<String, String> {
    let npm = node::get_npm_path();
    
    let output = Command::new(&npm)
        .args(&["install", "-g", "openclaw"])
        .output()
        .map_err(|e| format!("OpenClaw 설치 실패: {}", e))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!("OpenClaw 설치 실패: {}", stderr));
    }

    let stdout = String::from_utf8_lossy(&output.stdout);
    Ok(format!("OpenClaw 설치 완료\n{}", stdout.trim()))
}

/// Generate openclaw.yaml config with GitHub Copilot
pub fn generate_config(token: &str) -> Result<String, String> {
    let home_dir = dirs::home_dir().ok_or("홈 디렉토리를 찾을 수 없습니다.")?;
    let openclaw_dir = home_dir.join(".openclaw");
    
    std::fs::create_dir_all(&openclaw_dir)
        .map_err(|e| format!("설정 디렉토리 생성 실패: {}", e))?;

    let config_path = openclaw_dir.join("openclaw.yaml");

    // Don't overwrite existing config
    if config_path.exists() {
        return Ok("기존 설정 파일이 존재합니다. 유지합니다.".into());
    }

    let config = format!(
r#"# OpenClaw Configuration — auto-generated by auto-install-openclaw
# Docs: https://docs.openclaw.ai

llm:
  providers:
    - id: github-copilot
      type: copilot
      default: true

gateway:
  autostart: true
"#);

    std::fs::write(&config_path, config)
        .map_err(|e| format!("설정 파일 생성 실패: {}", e))?;

    Ok(format!("설정 파일 생성됨: {}", config_path.display()))
}

/// Start the OpenClaw gateway
pub fn start_gateway() -> Result<String, String> {
    let output = Command::new("openclaw")
        .args(&["gateway", "start"])
        .output()
        .map_err(|e| format!("Gateway 시작 실패: {}", e))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!("Gateway 시작 실패: {}", stderr));
    }

    Ok("Gateway 시작됨".into())
}

/// Register OpenClaw gateway as a startup program
pub fn register_autostart() -> Result<String, String> {
    // Use Windows Registry to add to startup
    let output = Command::new("reg")
        .args(&[
            "add",
            r"HKCU\Software\Microsoft\Windows\CurrentVersion\Run",
            "/v", "OpenClaw",
            "/t", "REG_SZ",
            "/d", "openclaw gateway start",
            "/f",
        ])
        .output()
        .map_err(|e| format!("시작프로그램 등록 실패: {}", e))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!("시작프로그램 등록 실패: {}", stderr));
    }

    Ok("시작프로그램 등록 완료".into())
}
